# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dof < Formula
  desc "Manage your dot files as a git bare repo"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "0.88"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/dof/releases/download/v0.88/dof_0.88_darwin_amd64.tar.gz"
      sha256 "ec89167b59ef03d3d3bc8f49b386233e8922c1fd058622c0e3ef476df3ac40ff"

      def install
        bin.install "dof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/dof/releases/download/v0.88/dof_0.88_darwin_arm64.tar.gz"
      sha256 "b422246e0f54cc2bfb9331325d436fe6e2fc82658a79bba693ac9190b55ea529"

      def install
        bin.install "dof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/dof/releases/download/v0.88/dof_0.88_linux_amd64.tar.gz"
        sha256 "f8b6923d609406ba14d4597db43eef9de4554d9868a552767fa994c07626d432"

        def install
          bin.install "dof"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/dof/releases/download/v0.88/dof_0.88_linux_arm64.tar.gz"
        sha256 "5fef774b0b915dfd24fdcdf5ea0455a4d64f0a457117cc3bba06af5981c6d9a2"

        def install
          bin.install "dof"
        end
      end
    end
  end
end
